<a href="https://colab.research.google.com/github/madhumithadasarathy/Oasis_Infobyte/blob/main/Car_price_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Importing necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#Loading the Dataset
df = pd.read_csv("/content/car data.csv")
df.head()

Car_Name  Year  Selling_Price  Present_Price  Driven_kms Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol   
1      sx4  2013           4.75           9.54       43000    Diesel   
2     ciaz  2017           7.25           9.85        6900    Petrol   
3  wagon r  2011           2.85           4.15        5200    Petrol   
4    swift  2014           4.60           6.87       42450    Diesel   

  Selling_type Transmission  Owner  
0       Dealer       Manual      0  
1       Dealer       Manual      0  
2       Dealer       Manual      0  
3       Dealer       Manual      0  
4       Dealer       Manual      0

In [ ]:
#Data description
df.describe()

Year  Selling_Price  Present_Price     Driven_kms       Owner
count   301.000000     301.000000     301.000000     301.000000  301.000000
mean   2013.627907       4.661296       7.628472   36947.205980    0.043189
std       2.891554       5.082812       8.642584   38886.883882    0.247915
min    2003.000000       0.100000       0.320000     500.000000    0.000000
25%    2012.000000       0.900000       1.200000   15000.000000    0.000000
50%    2014.000000       3.600000       6.400000   32000.000000    0.000000
75%    2016.000000       6.000000       9.900000   48767.000000    0.000000
max    2018.000000      35.000000      92.600000  500000.000000    3.000000

In [ ]:
#Data Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Car_Name       301 non-null    object 
 1   Year           301 non-null    int64  
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Driven_kms     301 non-null    int64  
 5   Fuel_Type      301 non-null    object 
 6   Selling_type   301 non-null    object 
 7   Transmission   301 non-null    object 
 8   Owner          301 non-null    int64  
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB


In [ ]:
#Checking for null values.
df.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Driven_kms       0
Fuel_Type        0
Selling_type     0
Transmission     0
Owner            0
dtype: int64

In [ ]:
#Columns of the Dataset
df.columns

Index(['Car_Name', 'Year', 'Selling_Price', 'Present_Price', 'Driven_kms',
       'Fuel_Type', 'Selling_type', 'Transmission', 'Owner'],
      dtype='object')

In [ ]:
#Fuel Types
df['Fuel_Type'].value_counts()

Petrol    239
Diesel     60
CNG         2
Name: Fuel_Type, dtype: int64

In [ ]:
#Transmission
df['Transmission'].value_counts()

Manual       261
Automatic     40
Name: Transmission, dtype: int64

In [ ]:
#Selling Type
df['Selling_type'].value_counts()

Dealer        195
Individual    106
Name: Selling_type, dtype: int64

In [ ]:
#Owners
df['Owner'].value_counts()

0    290
1     10
3      1
Name: Owner, dtype: int64

In [ ]:
#Encoding categorical variables
df=pd.get_dummies(df, columns=['Transmission','Selling_type','Owner','Fuel_Type'], drop_first=True)

In [ ]:
#Dropping unnecessary columns
df.drop(columns=['Owner_1','Fuel_Type_Diesel','Car_Name','Year'],inplace=True)
df.head()

Selling_Price  Present_Price  Driven_kms  Transmission_Manual  \
0           3.35           5.59       27000                    1   
1           4.75           9.54       43000                    1   
2           7.25           9.85        6900                    1   
3           2.85           4.15        5200                    1   
4           4.60           6.87       42450                    1   

   Selling_type_Individual  Owner_3  Fuel_Type_Petrol  
0                        0        0                 1  
1                        0        0                 0  
2                        0        0                 1  
3                        0        0                 1  
4                        0        0                 0

In [ ]:
#Seperating the feature and target columns
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [ ]:
#Splitting the dataset into training set and test set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [ ]:
#Scaling the values
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [ ]:
X_train

array([[ 0.31576107, -0.00279187,  0.93964891,  0.37590471, -0.76088591,
        -0.06917145],
       [ 0.9284886 ,  0.45550474, -0.69259787,  0.37590471, -0.76088591,
        -0.06917145],
       [-0.65763551, -0.53856243,  0.2823926 ,  0.37590471, -0.76088591,
        -0.06917145],
       ...,
       [-0.68837435, -0.62476584, -0.57390545,  0.37590471,  1.31425748,
        -0.06917145],
       [-0.69862063, -0.3792498 ,  0.63918345,  0.37590471, -0.76088591,
        -0.06917145],
       [-0.83182227, -0.76225482, -0.58104126,  0.37590471,  1.31425748,
        -0.06917145]])

In [ ]:
X_test

array([[ 5.70927336e-01,  2.43733689e-01,  9.07397174e-01,
         4.26401433e-01, -6.83916614e-01,  0.00000000e+00],
       [-8.46243239e-01, -9.40361945e-01, -9.42962753e-01,
         4.26401433e-01,  1.46216655e+00,  0.00000000e+00],
       [ 2.23451780e-02, -2.67247632e-01, -3.18903550e-01,
         4.26401433e-01, -6.83916614e-01,  0.00000000e+00],
       [ 7.99503235e-01,  5.47560420e-01, -7.84288070e-03,
         4.26401433e-01, -6.83916614e-01,  0.00000000e+00],
       [ 2.35381935e+00,  1.67586242e+00, -6.42259635e-01,
        -2.34520788e+00, -6.83916614e-01,  0.00000000e+00],
       [ 6.80603578e-02, -2.29959806e-01, -9.56327336e-01,
         4.26401433e-01, -6.83916614e-01,  0.00000000e+00],
       [-2.51945901e-01, -1.16715297e-01,  2.59695143e-02,
         4.26401433e-01, -6.83916614e-01,  0.00000000e+00],
       [-8.55386275e-01, -9.78478389e-01, -1.11002004e+00,
         4.26401433e-01,  1.46216655e+00,  0.00000000e+00],
       [-1.14800361e-01, -1.16715297e-01, -7.426

In [ ]:
#Building the model
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [ ]:
#Predicting values
pred_train = reg.predict(X_train)
pred_test = reg.predict(X_test)

In [ ]:
pred_train

array([ 0.60361729,  0.60616176,  0.90953646,  0.68691419,  1.0160887 ,
        1.03675114,  1.00649816,  0.99911226,  0.81831697,  0.83174386,
        0.83996411,  0.96851959,  0.86329916,  1.01013386,  1.02664185,
        0.8186665 ,  0.81963215,  0.71444331,  0.84366357,  0.55046156,
        0.88305306,  1.01930038,  1.00733059,  0.69787275,  0.34117542,
        1.01848559,  0.64773744,  0.73967486,  1.0055923 ,  0.9066527 ,
        1.00647098,  0.81338963,  0.61126832,  1.04234654,  0.63522241,
        0.7735451 ,  0.81284736,  0.99255404,  0.76961128,  0.89291624,
        0.75897877,  0.09869777,  1.03167254,  0.77794019,  0.57392167,
        1.01285721,  0.88084786,  0.95898138,  0.76765386,  0.86076021,
        0.99738599,  0.70862193,  0.98119455,  0.99789989,  0.91987153,
        1.17614657,  0.95248328,  0.80922191,  0.82472599,  0.94511359,
        0.76907063,  1.0278783 ,  0.89530525,  0.45936621,  0.76818917,
        0.59896919,  0.2480426 , -0.01139829,  0.69954662,  0.35

In [ ]:
pred_test

array([ 0.55014298,  1.04662031,  0.77921164,  0.59133481,  0.40021074,
        0.82594042,  0.84686202,  1.0607412 ,  0.93393243,  0.83616047,
        0.914067  ,  1.05241   ,  0.79288652,  0.85846997,  0.65170542,
        0.35894011,  0.84478413,  0.7754107 ,  0.98609475,  1.00631239,
        0.90180283,  0.84268717,  0.92179855,  0.55366801,  0.90063551,
        1.0341023 ,  0.84609003,  0.9907401 ,  1.0278237 ,  0.98005974,
        0.80598421,  0.65574878,  0.98626153,  0.63850653,  0.82797282,
        1.01103122,  0.75606047,  0.78988064,  0.99970438,  0.60635782,
        0.677487  ,  0.4256503 ,  0.82567597,  0.79270901,  0.73563331,
        0.42141025,  0.98265901,  1.02034747,  0.74638624,  0.72153243,
        0.88634782,  0.93060928,  0.74700648,  0.21086072,  0.98036251,
        0.96160145,  1.00772932,  0.81690134,  0.75188168,  1.00233269,
        0.83220071,  0.66696834,  0.94748896, -0.19539108,  0.85293035,
        0.77432988,  0.5862169 ,  0.92007219,  1.18225043,  0.87

0.3116437603904876